package hiiragi283.ragium.api.data.recipe

import net.minecraft.advancements.Criterion
import net.minecraft.data.recipes.RecipeBuilder
import net.minecraft.data.recipes.RecipeOutput
import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.TagKey
import net.minecraft.world.item.Item
import net.minecraft.world.item.crafting.Recipe
import net.neoforged.neoforge.common.conditions.ICondition
import net.neoforged.neoforge.common.conditions.NotCondition
import net.neoforged.neoforge.common.conditions.TagEmptyCondition

/**
 * Ragiumで使用する[RecipeBuilder]の拡張インターフェース
 */
interface HTRecipeBuilder : RecipeBuilder {
    /**
     * 進捗はサポートしていません。
     */
    @Deprecated(message = "Advancements not supported", level = DeprecationLevel.ERROR)
    override fun unlockedBy(name: String, criterion: Criterion<*>): RecipeBuilder = throw UnsupportedOperationException()

    /**
     * レシピIDの生成は[getPrimalId]を介して行われます。
     */
    @Deprecated(message = "Recipe ID is generated by getPrimalId()", level = DeprecationLevel.ERROR)
    override fun getResult(): Item = throw UnsupportedOperationException()

    /**
     * 自動生成したレシピIDを返します。
     */
    fun getPrimalId(): ResourceLocation

    /**
     * [getPrimalId]を[prefix]で前置したIDで登録します。
     */
    fun savePrefixed(recipeOutput: RecipeOutput, prefix: String) {
        save(recipeOutput, getPrimalId().withPrefix(prefix))
    }

    /**
     * [getPrimalId]を[suffix]で後置したIDで登録します。
     */
    fun saveSuffixed(recipeOutput: RecipeOutput, suffix: String) {
        save(recipeOutput, getPrimalId().withSuffix(suffix))
    }

    /**
     * 文字列でのレシピID指定はサポートされていません。
     */
    @Deprecated(message = "String recipe id not supported", level = DeprecationLevel.ERROR)
    override fun save(recipeOutput: RecipeOutput, id: String): Unit = throw UnsupportedOperationException()

    override fun save(recipeOutput: RecipeOutput) {
        save(recipeOutput, getPrimalId())
    }

    //    Prefixed    //

    abstract class Prefixed(val prefix: String) : HTRecipeBuilder {
        abstract fun createRecipe(): Recipe<*>

        private val conditions: MutableList<ICondition> = mutableListOf()

        fun setTagCondition(tagKey: TagKey<Item>): Prefixed = addCondition(NotCondition(TagEmptyCondition(tagKey)))

        fun addCondition(condition: ICondition): Prefixed = apply {
            this.conditions.add(condition)
        }

        override fun group(groupName: String?): RecipeBuilder = throw UnsupportedOperationException()

        final override fun save(recipeOutput: RecipeOutput, id: ResourceLocation) {
            recipeOutput.accept(
                id.withPrefix("$prefix/"),
                createRecipe(),
                null,
                *conditions.toTypedArray(),
            )
        }
    }
}
