package hiiragi283.ragium.api.data.recipe

import net.minecraft.advancements.Criterion
import net.minecraft.data.recipes.RecipeBuilder
import net.minecraft.data.recipes.RecipeOutput
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.item.Item
import net.minecraft.world.item.crafting.Recipe

/**
 * Ragiumで使用する[RecipeBuilder]の拡張インターフェース
 * @param R レシピのクラス
 */
interface HTRecipeBuilder<R : Recipe<*>> : RecipeBuilder {
    /**
     * 進捗はサポートしていません。
     */
    @Deprecated("Advancements not supported")
    override fun unlockedBy(name: String, criterion: Criterion<*>): RecipeBuilder = throw UnsupportedOperationException()

    /**
     * レシピIDの生成は[getPrimalId]を介して行われます。
     */
    @Deprecated("Recipe ID is generated by getPrimalId()")
    override fun getResult(): Item = throw UnsupportedOperationException()

    /**
     * 自動生成したレシピIDを返します。
     */
    fun getPrimalId(): ResourceLocation

    /**
     * [getPrimalId]を[prefix]で前置したIDで登録します。
     */
    fun savePrefixed(recipeOutput: RecipeOutput, prefix: String) {
        save(recipeOutput, getPrimalId().withPrefix(prefix))
    }

    /**
     * [getPrimalId]を[suffix]で後置したIDで登録します。
     */
    fun saveSuffixed(recipeOutput: RecipeOutput, suffix: String) {
        save(recipeOutput, getPrimalId().withSuffix(suffix))
    }

    override fun save(recipeOutput: RecipeOutput) {
        save(recipeOutput, getPrimalId())
    }

    /**
     * レシピIDの重複を回避するために使われる接頭辞
     */
    val prefix: String

    /**
     * 生成したレシピのインスタンスを返します。
     */
    fun createRecipe(): R

    override fun save(recipeOutput: RecipeOutput, id: ResourceLocation) {
        recipeOutput.accept(
            id.withPrefix("$prefix/"),
            createRecipe(),
            null,
        )
    }
}
